# Generated by Django 5.2.4 on 2025-07-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_lostfounditem_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostfounditem',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
