# Generated by Django 5.2.4 on 2025-07-19 00:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_lostfounditem_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='lostfounditem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='lf_search_idx'),
        ),
    ]
