# Generated by Django 5.2.4 on 2025-07-19 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_lostfounditem_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lostfounditem',
            name='lf_search_idx',
        ),
        migrations.RemoveField(
            model_name='lostfounditem',
            name='search_vector',
        ),
    ]
